rootFolder: /home/albertzard/repositories
editCommand: vim
repositories:
- nickname: nvim
  folderName: neofolder
  url: https://github.com/neovim/neovim
  sparse: true
- nickname: animated
  folderName: animated_folder
  url: https://github.com/new-data-services/tailwindcss-animated
  sparse: false
- nickname: log
  folderName: logseq-awesome
  url: https://github.com/logseq/awesome-logseq
  sparse: false
