rootFolder: /home/albertzard/repositories
editCommand: vim

repositories:
  - url: https://github.com/neovim/neovim
    nickname: nvim
    folderName: neofolder
    private_key: ""

  - url: https://github.com/new-data-services/tailwindcss-animated
    nickname: animated
    folderName: animated_folder
    private_key: ""
